server:
  port: 8080
#  servlet:
#    context-path: /api

spring:
  application:
    name: commuter-car-backend
  profiles:
    active: dev

# mybatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #mybatis-plus自动打开驼峰映射，mybatis则自动关闭
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1 #被删除
      logic-not-delete-value: 0 #正常

# 日志配置
logging:
  level:
    com:
      weng:
        commutercarbackend:
          mapper: debug
          service: debug
          controller: debug

# jwt配置
application:
#  wechat:
#    appid: wx189816a6dd169b25
#    secret: e8823d58ca24132ff55b2f2c1687a278
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970 #secert不能少于256bit，也就是32位字符
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.weng.commutercarbackend.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
